// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.
// Run `npm run generate` to regenerate from the endpoint manifest.
/* eslint-disable */
import * as q from "../params.js";
import type * as Types from "../types.js";
import type { ClientCore } from "../client.js";
import type { RequestOptions } from "../http.js";

export class Calendar {
  constructor(private readonly _c: ClientCore) {}

  /** Find the Adhik Maas (intercalary/leap month) in a given year — the extra lunar month inserted to sync the Hindu lunar calendar with the solar year. */
  adhikMaas<T = unknown>(input: { year: number; tz?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/calendar/adhik-maas", q.applyExtras(q.qNone(input), input, [["year", "year"], ["tz", "tz"]]), opts);
  }

  /** Get the Hindu calendar details for a Gregorian month — maps each day to its Hindu month (Chaitra/Vaishakha/…), paksha (Shukla/Krishna), tithi, and Vikram Samvat year. */
  month<T = unknown>(input: { date: string; tz: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/calendar/month", q.applyExtras(q.qNone(input), input, [["date", "date"], ["tz", "tz"]]), opts);
  }

  /** Get the current Hindu Ritu (season) for a date — one of 6 seasons: Vasanta (spring), Grishma (summer), Varsha (monsoon), Sharad (autumn), Hemanta (pre-winter), Shishira (winter). */
  ritu<T = unknown>(input: { date: string; tz: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/calendar/ritu", q.applyExtras(q.qNone(input), input, [["date", "date"], ["tz", "tz"]]), opts);
  }

  /** Get the Samvatsara (Jupiter year) name for a given year — the 60-year Jupiter cycle used in Hindu astrology (Prabhava, Vibhava, Shukla, … Akshaya). */
  samvatsara<T = unknown>(input: { date: string; tz: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/calendar/samvatsara", q.applyExtras(q.qNone(input), input, [["date", "date"], ["tz", "tz"]]), opts);
  }
}
