// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.
// Run `npm run generate` to regenerate from the endpoint manifest.
/* eslint-disable */
import * as q from "../params.js";
import type * as Types from "../types.js";
import type { ClientCore } from "../client.js";
import type { RequestOptions } from "../http.js";

export class Chart {
  constructor(private readonly _c: ClientCore) {}

  /** Ascendant (Lagna): sign, degree, nakshatra, pada and lord. */
  ascendant<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/chart/ascendant", q.qBirth(input), opts);
  }

  /** Sarvashtakavarga (SAV) grid; grand total is always 337. */
  ashtakvarga<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/chart/ashtakvarga", q.qBirth(input), opts);
  }

  /** One planet's Bhinnashtakavarga row: its benefic points (bindus) in each of the 12 signs. `planet` is Sun, Moon, Mars, Mercury, Jupiter, Venus or Saturn. */
  ashtakvargaPlanet<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { planet: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>(q.buildPath("/v1/chart/ashtakvarga/{planet}", input, ["planet"]), q.qBirth(input), opts);
  }

  /** Vedic graha drishti (planetary aspects) table. */
  aspects<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/chart/aspects", q.qBirth(input), opts);
  }

  /** Full birth-chart snapshot: avakhada, ascendant, all planets, sun/moon sign and birth panchang. */
  astroDetails<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/chart/astro-details", q.qBirth(input), opts);
  }

  /** Avakhada Chakra: varna, vashya, yoni, gana, nadi and lucky factors. */
  avakhada<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/chart/avakhada", q.qBirth(input), opts);
  }

  /** Compute Bhava Bala — the six-component strength of each of the 12 houses: Bhavadhipati Bala (lord strength), Bhava Digbala, Bhava Drishti Bala, and more. */
  bhavabala<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/chart/bhavabala", q.qBirth(input), opts);
  }

  /** Check which planets are combust (too close to the Sun) in a birth chart — returns each planet's angular distance from Sun, whether it is combust by classical limits, and combust severity. */
  combustion<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/chart/combustion", q.qBirth(input), opts);
  }

  /** Every planet's dignity (exalted/debilitated/own/friend/enemy/neutral). */
  dignity<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/chart/dignity", q.qBirth(input), opts);
  }

  /** Any divisional (varga) chart, e.g. D1, D9, D10, D60. */
  divisional<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { varga: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>(q.buildPath("/v1/chart/divisional/{varga}", input, ["varga"]), q.qBirth(input), opts);
  }

  /** Ghatak Chakra (inauspicious indicators) for the chart. */
  ghatak<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/chart/ghatak", q.qBirth(input), opts);
  }

  /** Identify Graha Yuddha (planetary war) in a birth chart — occurs when two visible planets are within 1° of each other. */
  grahaYuddha<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/chart/graha-yuddha", q.qBirth(input), opts);
  }

  /** List all planets occupying each of the 12 houses in a birth chart — a house-indexed view of the chart (vs planet-indexed from chart_planets). */
  houseOccupants<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/chart/house-occupants", q.qBirth(input), opts);
  }

  /** 12 house cusps / occupants for the chosen house system. */
  houses<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/chart/houses", q.qBirth(input), opts);
  }

  /** Get KP (Krishnamurti Paddhati) house significators for a given cusp — lists planets that significate the house through occupancy, lordship, and sub-lord chain. */
  kpHouseSignificator<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { cusp: number }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/chart/kp-house-significator", q.applyExtras(q.qBirth(input), input, [["cusp", "cusp"]]), opts);
  }

  /** Get the KP sublord of a planet — the sub-lord of the nakshatra sub-division the planet occupies (KP star lord → sub lord → sub-sub lord chain). */
  kpSublord<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { planet: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/chart/kp-sublord", q.applyExtras(q.qBirth(input), input, [["planet", "planet"]]), opts);
  }

  /** Birth (Janma) nakshatra and pada. */
  nakshatra<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/chart/nakshatra", q.qBirth(input), opts);
  }

  /** Navamsa (D9) divisional chart — convenience alias for divisional('D9'). */
  navamsa<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/chart/divisional/D9", q.qBirth(input), opts);
  }

  /** Detail for a single planet (sun|moon|mars|mercury|jupiter|venus|saturn|rahu|ketu). */
  planet<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { name: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>(q.buildPath("/v1/chart/planet/{name}", input, ["name"]), q.qBirth(input), opts);
  }

  /** All 9 grahas with sign, degree, nakshatra, house, retrograde, dignity, combustion and speed. */
  planets<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/chart/planets", q.qBirth(input), opts);
  }

  /** Shadbala (six-fold strength) for all 7 planets with components. */
  shadbala<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/chart/shadbala", q.qBirth(input), opts);
  }

  /** One shadbala component (sthana|dig|kala|chesta|naisargika|drik) for all planets. */
  shadbalaComponent<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { component: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>(q.buildPath("/v1/chart/shadbala/{component}", input, ["component"]), q.qBirth(input), opts);
  }
}
