// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.
// Run `npm run generate` to regenerate from the endpoint manifest.
/* eslint-disable */
import * as q from "../params.js";
import type * as Types from "../types.js";
import type { ClientCore } from "../client.js";
import type { RequestOptions } from "../http.js";

export class Eclipses {
  constructor(private readonly _c: ClientCore) {}

  /** All eclipses (solar + lunar) in a date range. */
  all<T = unknown>(input: Types.DateRangeInput & { lat?: number; lon?: number }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/eclipses/all", q.applyExtras(q.qDateRange(input), input, [["lat", "lat"], ["lon", "lon"]]), opts);
  }

  /** Lunar eclipses in a date range (optionally visible from a location). */
  lunar<T = unknown>(input: Types.DateRangeInput & { lat?: number; lon?: number }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/eclipses/lunar", q.applyExtras(q.qDateRange(input), input, [["lat", "lat"], ["lon", "lon"]]), opts);
  }

  /** Solar eclipses in a date range (optionally visible from a location). */
  solar<T = unknown>(input: Types.DateRangeInput & { lat?: number; lon?: number }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/eclipses/solar", q.applyExtras(q.qDateRange(input), input, [["lat", "lat"], ["lon", "lon"]]), opts);
  }
}
