// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.
// Run `npm run generate` to regenerate from the endpoint manifest.
/* eslint-disable */
import * as q from "../params.js";
import type * as Types from "../types.js";
import type { ClientCore } from "../client.js";
import type { RequestOptions } from "../http.js";

export class Festivals {
  constructor(private readonly _c: ClientCore) {}

  /** Hindu festivals and observances in a Gregorian month. */
  month<T = unknown>(input: { year: number; month: number; tz: string; region?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/festivals/month", q.applyExtras(q.qNone(input), input, [["year", "year"], ["month", "month"], ["tz", "tz"], ["region", "region"]]), opts);
  }

  /** List Hindu festivals and observances falling on a specific date — Ekadashi, Pradosh, Purnima, Amavasya, major festivals, vratas, and regional observances. */
  onDate<T = unknown>(input: { date: string; tz?: string; region?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/festivals/on-date", q.applyExtras(q.qNone(input), input, [["date", "date"], ["tz", "tz"], ["region", "region"]]), opts);
  }
}
