// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.
// Run `npm run generate` to regenerate from the endpoint manifest.
/* eslint-disable */
import * as q from "../params.js";
import type * as Types from "../types.js";
import type { ClientCore } from "../client.js";
import type { RequestOptions } from "../http.js";

export class Geo {
  constructor(private readonly _c: ClientCore) {}

  /** Full details for a place by its geo id. */
  place<T = unknown>(input: { id: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>(q.buildPath("/v1/geo/place/{id}", input, ["id"]), q.qNone(input), opts);
  }

  /** Reverse geocode coordinates to the nearest place (free). */
  reverse<T = unknown>(input: { lat: number; lon: number; limit?: number }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/geo/reverse", q.applyExtras(q.qNone(input), input, [["lat", "lat"], ["lon", "lon"], ["limit", "limit"]]), opts);
  }

  /** Search for a city or place by name — returns matching locations with latitude, longitude, state/province, country, and IANA timezone. */
  search<T = unknown>(input: { q: string; limit?: number; cc?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/geo/search", q.applyExtras(q.qNone(input), input, [["q", "q"], ["limit", "limit"], ["cc", "cc"]]), opts);
  }

  /** Get the IANA timezone for a latitude/longitude — returns timezone name (e.g. */
  timezone<T = unknown>(input: { lat: number; lon: number }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/geo/timezone", q.applyExtras(q.qNone(input), input, [["lat", "lat"], ["lon", "lon"]]), opts);
  }
}
