// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.
// Run `npm run generate` to regenerate from the endpoint manifest.
/* eslint-disable */
import * as q from "../params.js";
import type * as Types from "../types.js";
import type { ClientCore } from "../client.js";
import type { RequestOptions } from "../http.js";

export class Horoscope {
  constructor(private readonly _c: ClientCore) {}

  /** Daily horoscope by Moon sign (rashi). */
  daily<T = unknown>(input: Types.RashiInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/horoscope/daily", q.qRashi(input), opts);
  }

  /** Monthly horoscope by rashi. */
  monthly<T = unknown>(input: Types.RashiInput & { month: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/horoscope/monthly", q.applyExtras(q.qRashi(input), input, [["month", "month"]]), opts);
  }

  /** Weekly horoscope by rashi. */
  weekly<T = unknown>(input: Types.RashiInput & { week: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/horoscope/weekly", q.applyExtras(q.qRashi(input), input, [["week", "week"]]), opts);
  }
}
