// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.
/* eslint-disable */
import type { ClientCore } from "../client.js";
import { Ashtakavarga } from "./ashtakavarga.js";
import { Calendar } from "./calendar.js";
import { Chart } from "./chart.js";
import { Dasha } from "./dasha.js";
import { Eclipses } from "./eclipses.js";
import { Festivals } from "./festivals.js";
import { Geo } from "./geo.js";
import { Horoscope } from "./horoscope.js";
import { Lalkitab } from "./lalkitab.js";
import { Meta } from "./meta.js";
import { Milan } from "./milan.js";
import { Muhurta } from "./muhurta.js";
import { Narrative } from "./narrative.js";
import { Numerology } from "./numerology.js";
import { Panchang } from "./panchang.js";
import { PlanetMoments } from "./planetMoments.js";
import { Prashna } from "./prashna.js";
import { Remedies } from "./remedies.js";
import { Reports } from "./reports.js";
import { Tarot } from "./tarot.js";
import { Transit } from "./transit.js";
import { Varshaphal } from "./varshaphal.js";
import { Western } from "./western.js";

/**
 * All resource namespaces, instantiated against a {@link ClientCore}. The
 * {@link LifeAstro} client extends this so namespaces are available as
 * `client.panchang`, `client.chart`, `client.western.natal`, etc.
 */
export class Resources {
  readonly ashtakavarga: Ashtakavarga;
  readonly calendar: Calendar;
  readonly chart: Chart;
  readonly dasha: Dasha;
  readonly eclipses: Eclipses;
  readonly festivals: Festivals;
  readonly geo: Geo;
  readonly horoscope: Horoscope;
  readonly lalkitab: Lalkitab;
  readonly meta: Meta;
  readonly milan: Milan;
  readonly muhurta: Muhurta;
  readonly narrative: Narrative;
  readonly numerology: Numerology;
  readonly panchang: Panchang;
  readonly planetMoments: PlanetMoments;
  readonly prashna: Prashna;
  readonly remedies: Remedies;
  readonly reports: Reports;
  readonly tarot: Tarot;
  readonly transit: Transit;
  readonly varshaphal: Varshaphal;
  readonly western: Western;

  constructor(core: ClientCore) {
    this.ashtakavarga = new Ashtakavarga(core);
    this.calendar = new Calendar(core);
    this.chart = new Chart(core);
    this.dasha = new Dasha(core);
    this.eclipses = new Eclipses(core);
    this.festivals = new Festivals(core);
    this.geo = new Geo(core);
    this.horoscope = new Horoscope(core);
    this.lalkitab = new Lalkitab(core);
    this.meta = new Meta(core);
    this.milan = new Milan(core);
    this.muhurta = new Muhurta(core);
    this.narrative = new Narrative(core);
    this.numerology = new Numerology(core);
    this.panchang = new Panchang(core);
    this.planetMoments = new PlanetMoments(core);
    this.prashna = new Prashna(core);
    this.remedies = new Remedies(core);
    this.reports = new Reports(core);
    this.tarot = new Tarot(core);
    this.transit = new Transit(core);
    this.varshaphal = new Varshaphal(core);
    this.western = new Western(core);
  }
}
