// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.
// Run `npm run generate` to regenerate from the endpoint manifest.
/* eslint-disable */
import * as q from "../params.js";
import type * as Types from "../types.js";
import type { ClientCore } from "../client.js";
import type { RequestOptions } from "../http.js";

export class Lalkitab {
  constructor(private readonly _c: ClientCore) {}

  /** Lal Kitab chart — planets mapped into Lal Kitab's fixed Aries-based houses. */
  chart<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/lalkitab/chart", q.qBirth(input), opts);
  }

  /** Full 35-year Lal Kitab dasha schedule — planet-ruled periods with start/end dates. */
  dasha<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/lalkitab/dasha", q.qBirth(input), opts);
  }

  /** Currently active Lal Kitab dasha planet and period window. */
  dashaCurrent<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/lalkitab/dasha/current", q.qBirth(input), opts);
  }
}
