// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.
// Run `npm run generate` to regenerate from the endpoint manifest.
/* eslint-disable */
import * as q from "../params.js";
import type * as Types from "../types.js";
import type { ClientCore } from "../client.js";
import type { RequestOptions } from "../http.js";

export class Meta {
  constructor(private readonly _c: ClientCore) {}

  /** The supported ayanamsa systems with each one's value in degrees on a date (defaults to today). Free (0 credits). */
  ayanamsas<T = unknown>(input: Types.InstantInput & Types.VedicMomentSettings = {}, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/meta/ayanamsas", q.qInstant(input), opts);
  }

  /** Every API route with its credit cost and group. Free (0 credits). */
  endpoints<T = unknown>(input: Record<string, never> = {}, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/meta/endpoints", q.qNone(input), opts);
  }

  /** Catalog of every dosha the API detects and narrates, with the IDs `narrative.dosha` accepts. Free (0 credits). */
  vedicDoshas<T = unknown>(input: Record<string, never> = {}, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/meta/vedic/doshas", q.qNone(input), opts);
  }

  /** The languages narrative endpoints can answer in, with corpus coverage for each. Free (0 credits). */
  vedicLocales<T = unknown>(input: Record<string, never> = {}, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/meta/vedic/locales", q.qNone(input), opts);
  }

  /** The axes narrative text can vary along (locale, regional pack). Free (0 credits). */
  vedicNarrativeAxes<T = unknown>(input: Record<string, never> = {}, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/meta/vedic/narrative-axes", q.qNone(input), opts);
  }

  /** Catalog of every yoga the API detects and narrates, with the IDs `narrative.yoga` accepts. Free (0 credits). */
  vedicYogas<T = unknown>(input: Record<string, never> = {}, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/meta/vedic/yogas", q.qNone(input), opts);
  }

  /** API build and ephemeris version. Free (0 credits). */
  version<T = unknown>(input: Record<string, never> = {}, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/meta/version", q.qNone(input), opts);
  }
}
