// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.
// Run `npm run generate` to regenerate from the endpoint manifest.
/* eslint-disable */
import * as q from "../params.js";
import type * as Types from "../types.js";
import type { ClientCore } from "../client.js";
import type { RequestOptions } from "../http.js";

export class Milan {
  constructor(private readonly _c: ClientCore) {}

  /** Full 36-point Ashtakoota breakdown across all 8 kootas. */
  ashtakoota<T = unknown>(input: Types.BoyGirlInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/milan/ashtakoota", q.qBoyGirl(input), opts);
  }

  /** One koota (varna|vashya|tara|yoni|graha_maitri|gana|bhakoot|nadi). */
  ashtakootaKoota<T = unknown>(input: Types.BoyGirlInput & Types.VedicMomentSettings & { koota: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>(q.buildPath("/v1/milan/ashtakoota/{koota}", input, ["koota"]), q.qBoyGirl(input), opts);
  }

  /** Just the Ashtakoota (Guna Milan) total score and verdict. */
  ashtakootaTotal<T = unknown>(input: Types.BoyGirlInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/milan/ashtakoota/total", q.qBoyGirl(input), opts);
  }

  /** Check Dasha synchrony between two partners — are they running compatible mahadasha lords at the same time? Good dasha synchrony indicates the couple will flourish together during major life events. */
  dashaSync<T = unknown>(input: Types.BoyGirlInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/milan/dasha-sync", q.qBoyGirl(input), opts);
  }

  /** Check Dhan Yog (wealth yoga) for a single person's chart — assesses 2nd/11th house lord strength and Jupiter placement for prosperity. */
  dhanYog<T = unknown>(input: Types.BirthInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/milan/dhan-yog", q.qBirthPrefixed(input), opts);
  }

  /** Assess longevity for a single person's chart — classical analysis of lagna, 8th house, and Moon sign longevity indicators. */
  longevity<T = unknown>(input: Types.BirthInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/milan/longevity", q.qBirthPrefixed(input), opts);
  }

  /** Check Mahendra Koota — the 4th additional compatibility factor beyond Ashtakoota. */
  mahendra<T = unknown>(input: Types.BoyGirlInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/milan/mahendra", q.qBoyGirl(input), opts);
  }

  /** Mangal Dosha (Manglik) detection for one chart. */
  mangalDosha<T = unknown>(input: Types.BirthInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/milan/mangal-dosha", q.qBirthPrefixed(input), opts);
  }

  /** Nadi dosha detection plus exceptions. */
  nadiDosha<T = unknown>(input: Types.BoyGirlInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/milan/nadi-dosha", q.qBoyGirl(input), opts);
  }

  /** Check Navamsa compatibility — compares the D9 (Navamsa) chart placements of both partners for deeper marriage harmony beyond the D1 chart. */
  navamsaCompat<T = unknown>(input: Types.BoyGirlInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/milan/navamsa-compat", q.qBoyGirl(input), opts);
  }

  /** Check Santan Yog for a single person's chart — assesses 5th house lord and Jupiter placement to indicate prospects for children. */
  santanYog<T = unknown>(input: Types.BirthInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/milan/santan-yog", q.qBirthPrefixed(input), opts);
  }

  /** Check Shani Dosha for a single person's chart — Saturn in 1st, 4th, 7th, 10th, or 12th house from lagna. */
  shaniDosha<T = unknown>(input: Types.BirthInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/milan/shani-dosha", q.qBirthPrefixed(input), opts);
  }

  /** Check Stree Dirgha — the distance from bride's nakshatra to groom's must be more than 9 nakshatras for a beneficial match (indicates the groom will lead a longer, more prosperous life than the bride expected). */
  streeDirgha<T = unknown>(input: Types.BoyGirlInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/milan/stree-dirgha", q.qBoyGirl(input), opts);
  }

  /** Vivah Phal (marriage-outcome) assessment for one chart. */
  vivahPhal<T = unknown>(input: Types.BirthInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/milan/vivah-phal", q.qBirthPrefixed(input), opts);
  }
}
