// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.
// Run `npm run generate` to regenerate from the endpoint manifest.
/* eslint-disable */
import * as q from "../params.js";
import type * as Types from "../types.js";
import type { ClientCore } from "../client.js";
import type { RequestOptions } from "../http.js";

export class Narrative {
  constructor(private readonly _c: ClientCore) {}

  /** Get a multi-paragraph career and profession narrative for a Vedic birth chart — analyses the 10th house lord, planets in the 10th, D10 chart, and dashas to describe career strengths, suitable professions, and current period's impact on work. */
  careerOutlook<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/career-outlook", q.applyExtras(q.qBirth(input), input, [["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get the Dasha Phal (period interpretation) narrative for the currently running Vimshottari Mahadasha + Antardasha combination — a human-readable explanation of what this dasha pair typically brings and how it interacts with the natal chart. */
  dashaPhal<T = unknown>(input: Types.BirthInput & Types.VedicMomentSettings & { date?: string; tz?: string; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/dasha-phal", q.applyExtras(q.qBirthPrefixed(input), input, [["date", "date"], ["tz", "tz"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get narrative interpretations for a specific dasha combination — pass mahadasha lord (and optionally antardasha lord) to get the meaning of that specific period for the natal chart. */
  dashaTreePhal<T = unknown>(input: Types.BirthInput & Types.VedicMomentSettings & { maha: string; antar?: string; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/dasha-tree-phal", q.applyExtras(q.qBirthPrefixed(input), input, [["maha", "maha"], ["antar", "antar"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Narrative interpretation of a divisional (varga) chart. */
  divisional<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { varga: string; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>(q.buildPath("/v1/vedic/narrative/divisional/{varga}", input, ["varga"]), q.applyExtras(q.qBirth(input), input, [["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Narrative interpretation of a specific dosha in the chart. */
  dosha<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { id: string; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>(q.buildPath("/v1/vedic/narrative/dosha/{id}", input, ["id"]), q.applyExtras(q.qBirth(input), input, [["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get the Doshas narrative for a birth chart — comprehensive analysis of all major afflictions (Mangal Dosha, Kaal Sarp Dosha, Pitru Dosha, Shrapit Dosha, Guru Chandal Yoga, Grahan Yoga) with presence, severity, cancellations, and remedial guidance. */
  doshas<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/doshas", q.applyExtras(q.qBirth(input), input, [["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get a finance and wealth narrative for a Vedic birth chart — analyses the 2nd and 11th house lords, Jupiter, Venus, and wealth yogas to describe financial strengths, challenges, and periods of prosperity. */
  financeOutlook<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/finance-outlook", q.applyExtras(q.qBirth(input), input, [["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get a personalised daily horoscope narrative computed from the rising sign (lagna) of a birth chart — more precise than generic Moon-sign horoscopes since it uses the exact birth data. The input is the birth chart; pass `onDate` (YYYY-MM-DD) to read a day other than today. */
  horoscopeDailyByLagna<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { onDate?: string; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/horoscope/daily-by-lagna", q.applyExtras(q.qBirth(input), input, [["onDate", "transit_date"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get a personalised daily horoscope narrative computed from the natal Moon sign with full transit context — richer than a generic rashifal because it uses the birth chart's Moon degree and current transit aspects. The input is the birth chart; pass `onDate` (YYYY-MM-DD) to read a day other than today. */
  horoscopeDailyByMoon<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { onDate?: string; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/horoscope/daily-by-moon", q.applyExtras(q.qBirth(input), input, [["onDate", "transit_date"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get a daily horoscope in Tamil astrology style — uses the Tamil rashi system and traditional Tamil Panchangam for the day's reading. The input is the birth chart; pass `onDate` (YYYY-MM-DD) to read a day other than today. */
  horoscopeDailyTamil<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { onDate?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/horoscope/daily-tamil", q.applyExtras(q.qBirth(input), input, [["onDate", "transit_date"]]), opts);
  }

  /** Get a personalised weekly horoscope narrative computed from the birth chart's rising sign (lagna) — personalised 7-day outlook with major transit themes. The input is the birth chart; pass `onDate` (YYYY-MM-DD) to read a day other than today. */
  horoscopeWeeklyByLagna<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { onDate?: string; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/horoscope/weekly-by-lagna", q.applyExtras(q.qBirth(input), input, [["onDate", "transit_date"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get a personalised weekly horoscope narrative computed from the natal Moon sign — personalised weekly reading using the birth chart's Moon degree. The input is the birth chart; pass `onDate` (YYYY-MM-DD) to read a day other than today. */
  horoscopeWeeklyByMoon<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { onDate?: string; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/horoscope/weekly-by-moon", q.applyExtras(q.qBirth(input), input, [["onDate", "transit_date"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get a narrative interpretation of a specific house lord's placement — where the lord of house N is placed in the chart and what it means for the areas of life that house governs. */
  houseLord<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { house: number; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/house-lord", q.applyExtras(q.qBirth(input), input, [["house", "house"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get a comprehensive narrative overview of all 12 house lords' placements in a birth chart — a full bhavesh analysis summarising how each house lord's position shapes the chart. */
  houseLordsOverview<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/house-lords-overview", q.applyExtras(q.qBirth(input), input, [["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get the Jaimini Chara Karakas for a birth chart — the 8 karaka planets (Atmakaraka, Amatyakaraka, Bhratrukaraka, Matrukaraka, Putrakaraka, Gnatikaraka, Darakaraka, Dara/Swamsha) determined by planet degrees, with interpretation. */
  karakas<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/karakas", q.applyExtras(q.qBirth(input), input, [["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get a narrative interpretation of the birth chart's lagna (ascendant) — describes the physical appearance, personality, health tendencies, and life approach associated with the rising sign, including first-house planets' influence. */
  lagna<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/lagna", q.applyExtras(q.qBirth(input), input, [["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get a marriage and relationship narrative for a Vedic birth chart — analyses the 7th house lord, Venus, navamsa, and marriage-timing dashas to describe relationship characteristics, likely spouse traits, and timing of marriage. */
  marriageOutlook<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/marriage-outlook", q.applyExtras(q.qBirth(input), input, [["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get a narrative compatibility analysis for a couple — goes beyond the numeric Ashtakoota score with a written interpretation of compatibility across all factors (guna milan, mangal dosha, dashas, navamsa). */
  milan<T = unknown>(input: { boyDate: string; boyTime: string; boyTz: string; girlDate: string; girlTime: string; girlTz: string; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/milan", q.applyExtras(q.qNone(input), input, [["boyDate", "boy.date"], ["boyTime", "boy.time"], ["boyTz", "boy.tz"], ["girlDate", "girl.date"], ["girlTime", "girl.time"], ["girlTz", "girl.tz"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get a narrative interpretation of the natal Moon sign (Chandra Rashi) — covers emotional nature, mental tendencies, mother relationship, and instinctive responses associated with the Moon's sign placement. */
  moonSign<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/moon-sign", q.applyExtras(q.qBirth(input), input, [["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get a narrative interpretation of the birth nakshatra (Janma Nakshatra) — covers personality, strengths, weaknesses, compatible nakshatras, ruling deity, symbol, and life path themes of the nakshatra the Moon occupied at birth. */
  nakshatra<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/nakshatra", q.applyExtras(q.qBirth(input), input, [["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get a narrative interpretation of a specific planet's house placement in a Vedic birth chart — describes what that planet's position in that house means for the native's life areas, including classical significations and any classical yoga formation. */
  planetInHouse<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { planet: string; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/planet-in-house", q.applyExtras(q.qBirth(input), input, [["planet", "planet"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get a narrative interpretation of a specific planet's sign placement — describes how the planet expresses itself in that rashi, classical dignity/debility implications, and characteristic traits. */
  planetInSign<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { planet: string; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/planet-in-sign", q.applyExtras(q.qBirth(input), input, [["planet", "planet"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get narrative interpretations for ALL planets' house placements in a birth chart in a single call — the full house-placement reading for every graha. */
  planetsInHouses<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/planets-in-houses", q.applyExtras(q.qBirth(input), input, [["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get narrative interpretations for ALL planets' sign placements in a birth chart in a single call — the full sign-placement reading for every graha. */
  planetsInSigns<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/planets-in-signs", q.applyExtras(q.qBirth(input), input, [["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get a holistic birth chart profile narrative — an executive summary of the entire chart covering lagna, Moon sign, key planetary strengths/weaknesses, dominant yogas, current dasha, and life-theme highlights in a single comprehensive reading. */
  profile<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/profile", q.applyExtras(q.qBirth(input), input, [["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** The whole authored Vedic glossary: text that defines a concept (yogas, doshas, techniques) rather than interpreting one chart. Large (~800 KB); prefer `referenceFamily`. */
  reference<T = unknown>(input: { lang?: string } = {}, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/reference", q.applyExtras(q.qNone(input), input, [["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** The authored Vedic glossary for one concept family, e.g. `yoga`, `dosha`, `argala`. */
  referenceFamily<T = unknown>(input: { family: string; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>(q.buildPath("/v1/vedic/narrative/reference/{family}", input, ["family"]), q.applyExtras(q.qNone(input), input, [["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get a narrative of all past and future Sade Sati periods for a birth chart — written descriptions of each 7.5-year Saturn transit cycle with dates, life themes expected, and which phase (rising/peak/setting) the person experienced. */
  sadeSatiHistory<T = unknown>(input: Types.BirthInput & Types.VedicMomentSettings & { date?: string; tz?: string; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/sade-sati-history", q.applyExtras(q.qBirthPrefixed(input), input, [["date", "date"], ["tz", "tz"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get a narrative interpretation of the current Sade Sati phase (rising, peak, or setting) — what the current phase typically brings and remedies. */
  sadeSatiPhase<T = unknown>(input: Types.BirthInput & Types.VedicMomentSettings & { date?: string; tz?: string; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/sade-sati-phase", q.applyExtras(q.qBirthPrefixed(input), input, [["date", "date"], ["tz", "tz"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get the current Sade Sati status with narrative context — whether the person is in Sade Sati, which phase, start/end dates, and a written description of the current transit's meaning for their Moon sign. */
  sadeSatiStatus<T = unknown>(input: Types.BirthInput & Types.VedicMomentSettings & { date?: string; tz?: string; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/sade-sati-status", q.applyExtras(q.qBirthPrefixed(input), input, [["date", "date"], ["tz", "tz"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get a narrative interpretation of the natal Sun sign (Surya Rashi) — covers ego, identity, father, authority, vitality, and the life-purpose themes associated with the Sun's sidereal sign placement. */
  sunSign<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/sun-sign", q.applyExtras(q.qBirth(input), input, [["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get a narrative interpretation of the Ashtakavarga transit scores for a birth chart — written analysis of how current planetary transits score against the natal chart's benefic-point grid, with guidance on which transits are favourable or challenging. */
  transitAshtakavarga<T = unknown>(input: { birthDate: string; birthTime: string; birthTz: string; lat: number; lon: number; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/transit-ashtakavarga", q.applyExtras(q.qNone(input), input, [["birthDate", "birth.date"], ["birthTime", "birth.time"], ["birthTz", "birth.tz"], ["lat", "lat"], ["lon", "lon"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get a narrative of the Double Transit analysis — written explanation of which life events the current Jupiter-Saturn joint transit is activating in the chart, and when the confluence is strongest. */
  transitDouble<T = unknown>(input: Types.BirthInput & Types.VedicMomentSettings & { date?: string; tz?: string; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/transit-double", q.applyExtras(q.qBirthPrefixed(input), input, [["date", "date"], ["tz", "tz"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get the Transit Phal (gochar results) narrative — a written analysis of all current major planetary transits over the natal chart, their house positions from Moon, and the classical effects expected from each transit. */
  transitPhal<T = unknown>(input: Types.BirthInput & Types.VedicMomentSettings & { date?: string; tz?: string; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/transit-phal", q.applyExtras(q.qBirthPrefixed(input), input, [["date", "date"], ["tz", "tz"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get a narrative of the key themes for the current Varshaphal (solar-return) year — written analysis of the annual chart's varsha lord, muntha, annual lagna, and tajika yogas as a prediction for the year's major themes. */
  varshaphalThemes<T = unknown>(input: { birthDate: string; birthTime: string; birthTz: string; lat: number; lon: number; year: number; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/varshaphal-themes", q.applyExtras(q.qNone(input), input, [["birthDate", "birth.date"], ["birthTime", "birth.time"], ["birthTz", "birth.tz"], ["lat", "lat"], ["lon", "lon"], ["year", "year"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Personalised yearly Bhavishyafal (annual horoscope) for a target year. */
  yearlyBhavishyafal<T = unknown>(input: { date: string; time: string; tz: string; lat: number; lon: number; year: number }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/yearly-bhavishyafal", q.applyExtras(q.qNone(input), input, [["date", "birth.date"], ["time", "birth.time"], ["tz", "birth.tz"], ["lat", "lat"], ["lon", "lon"], ["year", "year"]]), opts);
  }

  /** Narrative interpretation of a specific yoga in the chart. */
  yoga<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { id: string; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>(q.buildPath("/v1/vedic/narrative/yoga/{id}", input, ["id"]), q.applyExtras(q.qBirth(input), input, [["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get a narrative of all major Vedic yogas present in a birth chart — Raja Yoga, Dhana Yoga, Parivartana Yoga, Kemadruma Yoga, Neecha Bhanga, Panchamahapurusha, and others — with presence, strength, and what each yoga means for the native. */
  yogas<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/vedic/narrative/yogas", q.applyExtras(q.qBirth(input), input, [["lang", "lang"], ["lang", "locale"]]), opts);
  }
}
