// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.
// Run `npm run generate` to regenerate from the endpoint manifest.
/* eslint-disable */
import * as q from "../params.js";
import type * as Types from "../types.js";
import type { ClientCore } from "../client.js";
import type { RequestOptions } from "../http.js";

export class Panchang {
  constructor(private readonly _c: ClientCore) {}

  /** Abhijit Muhurat (auspicious window around solar noon). */
  abhijit<T = unknown>(input: Types.MomentInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/panchang/abhijit", q.qMoment(input), opts);
  }

  /** Full advanced panchang: everything in basic plus all muhurta windows, Choghadiya, Hindu month, samvat and more. */
  advanced<T = unknown>(input: Types.MomentInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/panchang/advanced", q.qMoment(input), opts);
  }

  /** Amrit Kalam auspicious window. */
  amritKalam<T = unknown>(input: Types.MomentInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/panchang/amrit-kalam", q.qMoment(input), opts);
  }

  /** Composite basic panchang in one call: tithi, nakshatra, yoga, karana, vara, sun/moon rise & set. */
  basic<T = unknown>(input: Types.MomentInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/panchang/basic", q.qMoment(input), opts);
  }

  /** Brahma Muhurat window before sunrise. */
  brahmaMuhurat<T = unknown>(input: Types.MomentInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/panchang/brahma-muhurat", q.qMoment(input), opts);
  }

  /** Choghadiya periods (day + night). */
  choghadiya<T = unknown>(input: Types.MomentInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/panchang/choghadiya", q.qMoment(input), opts);
  }

  /** Durmuhurta inauspicious periods for the day. */
  durmuhurta<T = unknown>(input: Types.MomentInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/panchang/durmuhurta", q.qMoment(input), opts);
  }

  /** Gulika Kaal window. */
  gulika<T = unknown>(input: Types.MomentInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/panchang/gulika", q.qMoment(input), opts);
  }

  /** Hindu lunar month, paksha, samvat and adhik/kshaya detection. */
  hinduMonth<T = unknown>(input: Types.MomentInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/panchang/hindu-month", q.qMoment(input), opts);
  }

  /** Planetary hours (horas) for the day, or the hora at a given time. */
  hora<T = unknown>(input: Types.MomentInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/panchang/hora", q.qMoment(input), opts);
  }

  /** Get the Dinman (day length) and Ratriman (night length) for a date — the exact duration of daytime from sunrise to sunset and nighttime from sunset to next sunrise, in ghatis (1 ghati = 24 minutes). */
  horaDinman<T = unknown>(input: Types.MomentInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/panchang/hora-dinman", q.qMoment(input), opts);
  }

  /** Current karana (half-tithi). */
  karana<T = unknown>(input: Types.MomentInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/panchang/karana", q.qMoment(input), opts);
  }

  /** Lagna (rising sign) table for the day with start/end times for each sign. */
  lagnaTable<T = unknown>(input: Types.MomentInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/panchang/lagna-table", q.qMoment(input), opts);
  }

  /** Full-month panchang calendar (one entry per day). tz accepts an IANA name ("Asia/Kolkata"), a fixed offset ("+05:30") or decimal hours ("5.5"). Pass include: "sheet" for a complete printable Hindu calendar page: per-day tithi/nakshatra/moon-sign end-times ("27:07+" notation), kshaya days, moonrise/moonset, Hindu month, Vikram/Shaka samvat, moon phase and every festival of the day, plus the page header. */
  monthly<T = unknown>(input: { lat: number; lon: number; alt?: number; tz?: string; year: number; month: number; include?: string; locale?: string; monthSystem?: string; ayanamsa?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/panchang/monthly", q.applyExtras(q.qNone(input), input, [["lat", "lat"], ["lon", "lon"], ["alt", "alt"], ["tz", "tz"], ["year", "year"], ["month", "month"], ["include", "include"], ["locale", "locale"], ["monthSystem", "month_system"], ["ayanamsa", "ayanamsa"]]), opts);
  }

  /** Moonrise and moonset times. */
  moonriseMoonset<T = unknown>(input: Types.MomentInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/panchang/moonrise-moonset", q.qMoment(input), opts);
  }

  /** Moon's nakshatra with pada, lord and start/end at the moment. */
  nakshatra<T = unknown>(input: Types.MomentInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/panchang/nakshatra", q.qMoment(input), opts);
  }

  /** Personalised daily Tara Bala prediction relative to a birth nakshatra (index 0-26). */
  nakshatraPrediction<T = unknown>(input: Types.MomentInput & Types.VedicMomentSettings & { birthNak: number }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/panchang/nakshatra-prediction", q.applyExtras(q.qMoment(input), input, [["birthNak", "birth_nak"]]), opts);
  }

  /** Panchaka classification at the moment. */
  panchaka<T = unknown>(input: Types.MomentInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/panchang/panchaka", q.qMoment(input), opts);
  }

  /** Pradosh Kaal twilight window after sunset. */
  pradoshKaal<T = unknown>(input: Types.MomentInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/panchang/pradosh-kaal", q.qMoment(input), opts);
  }

  /** Rahu Kaal inauspicious window. */
  rahuKaal<T = unknown>(input: Types.MomentInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/panchang/rahu-kaal", q.qMoment(input), opts);
  }

  /** Get solar Sankranti (Sun's sign ingress) dates for a year — the exact moment the Sun enters each of the 12 sidereal signs, including Makar Sankranti (Capricorn), Mesh Sankranti (Aries/New Year), and all others. */
  sankranti<T = unknown>(input: { date: string; tz: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/panchang/sankranti", q.applyExtras(q.qNone(input), input, [["date", "date"], ["tz", "tz"]]), opts);
  }

  /** Siddha Yoga vara+nakshatra auspicious combination check. */
  siddhaYoga<T = unknown>(input: Types.MomentInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/panchang/siddha-yoga", q.qMoment(input), opts);
  }

  /** Quick 5-element panchang strip (tithi, nakshatra, yoga, karana, vara) plus sunrise/sunset. */
  summary<T = unknown>(input: Types.MomentInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/panchang/summary", q.qMoment(input), opts);
  }

  /** Sunrise and sunset times plus day length. */
  sunriseSunset<T = unknown>(input: Types.MomentInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/panchang/sunrise-sunset", q.qMoment(input), opts);
  }

  /** Current tithi (lunar day) with paksha, lord and transition timing. */
  tithi<T = unknown>(input: Types.MomentInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/panchang/tithi", q.qMoment(input), opts);
  }

  /** Hindu weekday (vara) and its ruling planet. */
  vara<T = unknown>(input: Types.MomentInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/panchang/vara", q.qMoment(input), opts);
  }

  /** Varjyam forbidden window based on the Moon's nakshatra. */
  varjyam<T = unknown>(input: Types.MomentInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/panchang/varjyam", q.qMoment(input), opts);
  }

  /** Yamaganda inauspicious window. */
  yamaganda<T = unknown>(input: Types.MomentInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/panchang/yamaganda", q.qMoment(input), opts);
  }

  /** Current panchang yoga (one of 27). */
  yoga<T = unknown>(input: Types.MomentInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/panchang/yoga", q.qMoment(input), opts);
  }
}
