// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.
// Run `npm run generate` to regenerate from the endpoint manifest.
/* eslint-disable */
import * as q from "../params.js";
import type * as Types from "../types.js";
import type { ClientCore } from "../client.js";
import type { RequestOptions } from "../http.js";

export class PlanetMoments {
  constructor(private readonly _c: ClientCore) {}

  /** Find the combustion window for a planet — the date range when the planet is too close to the Sun (within classical combust limits) and loses strength. */
  combustionWindow<T = unknown>(input: { planet: string; date: string; time?: string; tz: string; maxDays?: number }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/planet-moments/combustion-window", q.applyExtras(q.qNone(input), input, [["planet", "planet"], ["date", "date"], ["time", "time"], ["tz", "tz"], ["maxDays", "max_days"]]), opts);
  }

  /** A planet's sign ingresses (sankranti) in a date range. */
  ingress<T = unknown>(input: { planet: string; date: string; time?: string; tz: string; maxDays?: number }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/planet-moments/ingress", q.applyExtras(q.qNone(input), input, [["planet", "planet"], ["date", "date"], ["time", "time"], ["tz", "tz"], ["maxDays", "max_days"]]), opts);
  }

  /** A planet's retrograde windows (station retro -> station direct) in a date range. */
  retrogradeWindow<T = unknown>(input: { planet: string; date: string; time?: string; tz: string; maxDays?: number }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/planet-moments/retrograde-window", q.applyExtras(q.qNone(input), input, [["planet", "planet"], ["date", "date"], ["time", "time"], ["tz", "tz"], ["maxDays", "max_days"]]), opts);
  }

  /** Get the current speed and motion state of a planet — degrees per day, whether it is direct/retrograde/stationary, and its speed relative to mean motion. */
  speed<T = unknown>(input: { planet: string; date: string; time?: string; tz: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/planet-moments/speed", q.applyExtras(q.qNone(input), input, [["planet", "planet"], ["date", "date"], ["time", "time"], ["tz", "tz"]]), opts);
  }
}
