// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.
// Run `npm run generate` to regenerate from the endpoint manifest.
/* eslint-disable */
import * as q from "../params.js";
import type * as Types from "../types.js";
import type { ClientCore } from "../client.js";
import type { RequestOptions } from "../http.js";

export class Reports {
  constructor(private readonly _c: ClientCore) {}

  /** Generate a comprehensive Dasha Analysis report — the full Vimshottari dasha timeline with narrative interpretation for each Mahadasha period, key life events timing, and dasha-transit correlations. */
  dashaAnalysis<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { name?: string; place?: string; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/reports/dasha-analysis", q.applyExtras(q.qBirth(input), input, [["name", "name"], ["place", "place"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Generate a detailed daily horoscope report for a Moon sign — structured report with separate sections for career, love, finance, health, and daily guidance. */
  horoscopeDaily<T = unknown>(input: Types.RashiInput & { lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/reports/horoscope/daily", q.applyExtras(q.qRashi(input), input, [["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Generate a detailed monthly horoscope report for a Moon sign — structured report covering the month's major transit themes, weekly breakdown, and guidance for career, relationships, and finance for the full month. `month` is `YYYY-MM`. */
  horoscopeMonthly<T = unknown>(input: Types.RashiInput & { month: string; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/reports/horoscope/monthly", q.applyExtras(q.qRashi(input), input, [["month", "month"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Generate a detailed weekly horoscope report for a Moon sign — structured report covering the week's planetary movement, day-by-day highlights, and focus areas. */
  horoscopeWeekly<T = unknown>(input: Types.RashiInput & { lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/reports/horoscope/weekly", q.applyExtras(q.qRashi(input), input, [["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Generate the Brihad (comprehensive) Kundli report — the most detailed birth chart report covering chart analysis, all divisional charts (D1–D60), planetary strengths (Shadbala), ashtakavarga, all dashas, yogas, doshas, remedies, and lifetime predictions. */
  kundliBrihad<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { name?: string; place?: string; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/reports/kundli/brihad", q.applyExtras(q.qBirth(input), input, [["name", "name"], ["place", "place"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Generate a Detailed Kundli report — birth chart report with the planet positions table, full house-by-house analysis, major yogas, key doshas (Mangal/Kaal Sarp/Pitra), the Vimshottari Mahadasha timeline (current + upcoming), and birth panchang. For all divisional charts (D9/D10), Shadbala strengths, and life-area predictions, use the Brihad report. */
  kundliDetailed<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { name?: string; place?: string; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/reports/kundli/detailed", q.applyExtras(q.qBirth(input), input, [["name", "name"], ["place", "place"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Generate a Lite Kundli report — a concise birth chart summary with lagna, Moon sign, nakshatra, key planets, current dasha, and a brief personality reading. */
  kundliLite<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { name?: string; place?: string; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/reports/kundli/lite", q.applyExtras(q.qBirth(input), input, [["name", "name"], ["place", "place"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Generate a comprehensive Mangal Dosha report — full analysis of Mangal Dosha presence, sub-rules, all cancellation conditions checked, severity, impact on marriage, and detailed remedies with specific mantras, pujas, and gemstone guidance. */
  mangalDosha<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { name?: string; place?: string; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/reports/mangal-dosha", q.applyExtras(q.qBirth(input), input, [["name", "name"], ["place", "place"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Generate a comprehensive Match Making (Kundli Milan) report for a couple — full Ashtakoota analysis with all 8 kootas scored, Mangal Dosha compatibility, Dasha synchrony, Navamsa compatibility, and an overall written recommendation. */
  matchMaking<T = unknown>(input: Types.BoyGirlInput & Types.VedicMomentSettings & { boyName?: string; girlName?: string; boyPlace?: string; girlPlace?: string; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/reports/match-making", q.applyExtras(q.qBoyGirl(input), input, [["boyName", "boy.name"], ["girlName", "girl.name"], ["boyPlace", "boy.place"], ["girlPlace", "girl.place"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Generate a comprehensive Numerology report — calculates all key numbers (Driver/Mulank, Conductor/Bhagyank, Name number, Soul Urge, Personality, Destiny) from name and date of birth, with complete interpretation of each number's meaning and their combined influence. */
  numerology<T = unknown>(input: { name: string; place?: string; dob: string; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/reports/numerology", q.applyExtras(q.qNone(input), input, [["name", "name"], ["place", "place"], ["dob", "dob"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Generate a comprehensive Sade Sati report — covers current Sade Sati status, all past and upcoming cycles from birth to age 90, phase-by-phase narrative for the current or next cycle, and detailed remedies (mantras, donations, Shani puja guidance). */
  sadeSati<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { name?: string; place?: string; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/reports/sade-sati", q.applyExtras(q.qBirth(input), input, [["name", "name"], ["place", "place"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Generate a comprehensive Varshaphal (Solar Return) annual report — full annual chart with varsha lord, muntha, annual lagna, Tajika yogas, Mudda dasha timeline, and predictions for all 12 life areas for the current solar-return year. */
  varshaphal<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { name?: string; place?: string; year: number; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/reports/varshaphal", q.applyExtras(q.qBirth(input), input, [["name", "name"], ["place", "place"], ["year", "year"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }
}
