// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.
// Run `npm run generate` to regenerate from the endpoint manifest.
/* eslint-disable */
import * as q from "../params.js";
import type * as Types from "../types.js";
import type { ClientCore } from "../client.js";
import type { RequestOptions } from "../http.js";

export class Tarot {
  constructor(private readonly _c: ClientCore) {}

  /** Get the complete details for a single tarot card by ID — name, suit, element, archetype, upright and reversed meanings, keywords, and yes/no tendency. */
  card<T = unknown>(input: { id: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>(q.buildPath("/v1/tarot/card/{id}", input, ["id"]), q.qNone(input), opts);
  }

  /** List tarot cards from the 78-card Rider-Waite deck with upright/reversed meanings, keywords, and yes/no tendency. */
  cards<T = unknown>(input: { suit?: string; search?: string } = {}, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/tarot/cards", q.applyExtras(q.qNone(input), input, [["suit", "suit"], ["search", "search"]]), opts);
  }

  /** Get the card of the day — a deterministic daily tarot card that is the same for everyone on a given date. */
  daily<T = unknown>(input: { date?: string } = {}, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/tarot/daily", q.applyExtras(q.qNone(input), input, [["date", "date"]]), opts);
  }

  /** Draw a tarot spread with a chosen layout and optional topic focus. */
  spread<T = unknown>(input: { type: string; topic?: string; seed?: number }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/tarot/spread", q.applyExtras(q.qNone(input), input, [["type", "type"], ["topic", "topic"], ["seed", "seed"]]), opts);
  }

  /** Get a yes/no tarot answer — draws one card, returns yes/no/maybe based on the card's natural tendency modified by orientation, with reasoning. */
  yesNo<T = unknown>(input: { seed?: number } = {}, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/tarot/yes-no", q.applyExtras(q.qNone(input), input, [["seed", "seed"]]), opts);
  }
}
