// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.
// Run `npm run generate` to regenerate from the endpoint manifest.
/* eslint-disable */
import * as q from "../params.js";
import type * as Types from "../types.js";
import type { ClientCore } from "../client.js";
import type { RequestOptions } from "../http.js";

export class Transit {
  constructor(private readonly _c: ClientCore) {}

  /** Score current planetary transits against a natal chart using Ashtakavarga — shows which houses transiting planets are moving through and how many benefic points those signs have in the natal chart. */
  ashtakavarga<T = unknown>(input: Types.NatalTransitInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/transit/ashtakavarga", q.qNatalTransit(input), opts);
  }

  /** List the pairs of planets occupying the same sidereal sign at a moment (planetary conjunctions by sign). Takes a date, not a birth chart; defaults to today. */
  doubleTransit<T = unknown>(input: Types.InstantInput & Types.VedicMomentSettings = {}, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/transit/double-transit", q.qInstant(input), opts);
  }

  /** Current sidereal positions of all 9 grahas (defaults to now). */
  positions<T = unknown>(input: Types.InstantInput & Types.VedicMomentSettings = {}, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/transit/positions", q.qInstant(input), opts);
  }

  /** Saturn Sade Sati status (rising/peak/setting) relative to the birth Moon. */
  sadeSati<T = unknown>(input: Types.BirthInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/transit/sade-sati", q.qBirthPrefixed(input), opts);
  }

  /** Check whether a person is currently in Small Panoti (Ashtama Shani) — the 2.5-year Saturn transit through the 8th house from natal Moon, considered challenging. */
  smallPanoti<T = unknown>(input: Types.BirthInput & Types.VedicMomentSettings & { date?: string; time?: string; tz?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/transit/small-panoti", q.applyExtras(q.qBirthPrefixed(input), input, [["date", "date"], ["time", "time"], ["tz", "tz"]]), opts);
  }

  /** Get the complete history and future windows of Small Panoti (Ashtama Shani) for a natal chart — all past and upcoming 2.5-year periods when Saturn transits the 8th house from natal Moon. */
  smallPanotiHistory<T = unknown>(input: Types.BirthInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/transit/small-panoti/history", q.qBirthPrefixed(input), opts);
  }

  /** Compute Tara Bala for today's transiting Moon relative to a natal chart — rates the day as Janma/Sampat/Vipat/Kshema/Pratyak/Sadhana/Vadha/Mitra/Param-Mitra tara. */
  tarabala<T = unknown>(input: Types.NatalTransitInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/transit/tarabala", q.qNatalTransit(input), opts);
  }

  /** Check Vedha (transit obstruction) for a natal chart — certain house transits are blocked (vedha'd) by another planet transiting a specific opposing house simultaneously. */
  vedha<T = unknown>(input: Types.NatalTransitInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/transit/vedha", q.qNatalTransit(input), opts);
  }
}
