// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.
// Run `npm run generate` to regenerate from the endpoint manifest.
/* eslint-disable */
import * as q from "../params.js";
import type * as Types from "../types.js";
import type { ClientCore } from "../client.js";
import type { RequestOptions } from "../http.js";

export class Varshaphal {
  constructor(private readonly _c: ClientCore) {}

  /** Varshaphal (annual solar-return) chart for a year. */
  chart<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { year: number }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/varshaphal/chart", q.applyExtras(q.qBirth(input), input, [["year", "year"]]), opts);
  }

  /** Tajika Harsha Bala for the annual chart. */
  harshaBala<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { year: number }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/varshaphal/harsha-bala", q.applyExtras(q.qBirth(input), input, [["year", "year"]]), opts);
  }

  /** Get the Varsha Lord (year ruler) for an annual chart — the planet that rules the Varshaphal year based on the Tajika system. */
  lord<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { year: number }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/varshaphal/lord", q.applyExtras(q.qBirth(input), input, [["year", "year"]]), opts);
  }

  /** Varshaphal Mudda Dasha periods for the solar-return year. */
  muddaDasha<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { year: number }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/varshaphal/mudda-dasha", q.applyExtras(q.qBirth(input), input, [["year", "year"]]), opts);
  }

  /** Get Muntha placement for a Varshaphal year — Muntha moves one sign per year from birth lagna and its house position in the annual chart is a key indicator of the year's themes. */
  muntha<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { year: number }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/varshaphal/muntha", q.applyExtras(q.qBirth(input), input, [["year", "year"]]), opts);
  }

  /** Get the precise Julian Day (JD) and calendar datetime of the solar return for a given year — the exact moment the Sun returns to its natal longitude. */
  solarReturnJd<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { year: number }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/varshaphal/solar-return-jd", q.applyExtras(q.qBirth(input), input, [["year", "year"]]), opts);
  }

  /** Get Tajika Yogas in the Varshaphal annual chart — Ikkaval, Induvara, Ithasala, Ishrafa, Nakta, Yamaya, Manau, Khallasara, Duphali-Kuttha, and other Tajika aspect-based yogas that indicate the tone of the solar-return year. */
  yoga<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { year: number }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/varshaphal/yoga", q.applyExtras(q.qBirth(input), input, [["year", "year"]]), opts);
  }
}
