// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.
// Run `npm run generate` to regenerate from the endpoint manifest.
/* eslint-disable */
import * as q from "../params.js";
import type * as Types from "../types.js";
import type { ClientCore } from "../client.js";
import type { RequestOptions } from "../http.js";

class WesternAstrocartography {
  constructor(private readonly _c: ClientCore) {}

  /** Compute Local Space astrocartography — the directions from an observer's location in which each natal planet rises, sets, culminates, or anti-culminates. */
  localSpace<T = unknown>(input: Types.WesternNatalInput & { observerLat: number; observerLon: number }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/astrocartography/local-space", q.applyExtras(q.qWesternNatal(input), input, [["observerLat", "observer_lat"], ["observerLon", "observer_lon"]]), opts);
  }

  /** Astrocartography planet lines (ASC/DSC/MC/IC) for mapping. */
  planetLines<T = unknown>(input: Types.WesternMomentInput & { latStep?: number }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/astrocartography/planet-lines", q.applyExtras(q.qWesternMoment(input), input, [["latStep", "lat_step"]]), opts);
  }
}

class WesternCompatibility {
  constructor(private readonly _c: ClientCore) {}

  /** Get the Western sun-sign compatibility between two zodiac signs — score 0–100, band (excellent/good/fair/challenging), aspect basis (trine/sextile/square etc.), element interaction, strengths, and challenges. */
  sunSign<T = unknown>(input: { signA: string; signB: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/compatibility/sun-sign", q.applyExtras(q.qNone(input), input, [["signA", "sign_a"], ["signB", "sign_b"]]), opts);
  }
}

class WesternComposite {
  constructor(private readonly _c: ClientCore) {}

  /** Get aspects in the composite (midpoint) chart for two people — shows how the relationship's combined energy is configured. */
  aspects<T = unknown>(input: Types.TwoPersonInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/composite/aspects", q.qTwoPerson(input), opts);
  }

  /** Composite (midpoint) relationship chart. */
  chart<T = unknown>(input: Types.TwoPersonInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/composite/chart", q.qTwoPerson(input), opts);
  }

  /** Compute the house cusps of the Composite chart for two people — the midpoint chart combining both natal charts to represent the relationship itself. */
  houses<T = unknown>(input: Types.TwoPersonInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/composite/houses", q.qTwoPerson(input), opts);
  }

  /** Compute the planet placements in the Composite chart for two people — midpoint positions for all planets in the relationship chart. */
  planets<T = unknown>(input: Types.TwoPersonInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/composite/planets", q.qTwoPerson(input), opts);
  }
}

class WesternDavison {
  constructor(private readonly _c: ClientCore) {}

  /** Get aspects in the Davison relationship chart. */
  aspects<T = unknown>(input: Types.TwoPersonInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/davison/aspects", q.qTwoPerson(input), opts);
  }

  /** Compute the Davison relationship chart — an alternative to the composite chart that uses the midpoint of the two birth times rather than midpoint longitudes. */
  chart<T = unknown>(input: Types.TwoPersonInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/davison/chart", q.qTwoPerson(input), opts);
  }

  /** Compute the house cusps of the Davison Relationship chart — the chart for the midpoint in time and space between two people's births (an actual chart for a real moment, unlike the composite). */
  houses<T = unknown>(input: Types.TwoPersonInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/davison/houses", q.qTwoPerson(input), opts);
  }

  /** Compute the planet placements in the Davison Relationship chart — all planet positions in the Davison chart's tropical zodiac. */
  planets<T = unknown>(input: Types.TwoPersonInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/davison/planets", q.qTwoPerson(input), opts);
  }
}

class WesternDignities {
  constructor(private readonly _c: ClientCore) {}

  /** Compute the Almuten Figuris — the planet with the highest combined essential dignity score at the Ascendant degree. */
  almuten<T = unknown>(input: { ascLon: number; diurnal?: string; scheme?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/dignities/almuten", q.applyExtras(q.qNone(input), input, [["ascLon", "asc_lon"], ["diurnal", "diurnal"], ["scheme", "scheme"]]), opts);
  }

  /** Get the bound (term) ruler for a zodiac degree and the full sign breakdown — shows which planet rules each of the five bounds within a sign. */
  bounds<T = unknown>(input: { lon: number; scheme?: string; diurnal?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/dignities/bounds", q.applyExtras(q.qNone(input), input, [["lon", "lon"], ["scheme", "scheme"], ["diurnal", "diurnal"]]), opts);
  }

  /** Get the face (decan) ruler for a zodiac degree using the Chaldean order — shows which of the 36 faces the degree falls in and its planetary ruler. */
  face<T = unknown>(input: { lon: number; scheme?: string; diurnal?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/dignities/face", q.applyExtras(q.qNone(input), input, [["lon", "lon"], ["scheme", "scheme"], ["diurnal", "diurnal"]]), opts);
  }

  /** Essential dignities for a planet (domicile/exaltation/triplicity/bound/face + almuten). */
  planet<T = unknown>(input: { planet: string; lon: number; diurnal?: boolean; scheme?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/dignities/planet", q.applyExtras(q.qNone(input), input, [["planet", "planet"], ["lon", "lon"], ["diurnal", "diurnal"], ["scheme", "scheme"]]), opts);
  }

  /** Compute essential dignities and mutual receptions for a Western birth chart — each planet's essential dignity state (domicile, exaltation, triplicity, term, face, detriment, fall), any mutual reception pairs, and the overall dignity score. */
  receptions<T = unknown>(input: { sun?: number; moon?: number; mercury?: number; venus?: number; mars?: number; jupiter?: number; saturn?: number } = {}, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/dignities/receptions", q.applyExtras(q.qNone(input), input, [["sun", "sun"], ["moon", "moon"], ["mercury", "mercury"], ["venus", "venus"], ["mars", "mars"], ["jupiter", "jupiter"], ["saturn", "saturn"]]), opts);
  }

  /** Get the triplicity (element) ruler for a zodiac degree — shows which planet rules by fire/earth/air/water triplicity, with day and night rulers. */
  triplicity<T = unknown>(input: { lon: number; scheme?: string; diurnal?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/dignities/triplicity", q.applyExtras(q.qNone(input), input, [["lon", "lon"], ["scheme", "scheme"], ["diurnal", "diurnal"]]), opts);
  }
}

class WesternEclipses {
  constructor(private readonly _c: ClientCore) {}

  /** Upcoming solar and lunar eclipses (default 12 months ahead). */
  upcoming<T = unknown>(input: { months?: number } = {}, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/eclipses/upcoming", q.applyExtras(q.qNone(input), input, [["months", "months"]]), opts);
  }

  /** Check whether upcoming eclipses are visible from a specific location — returns visibility type (total, partial, annular, not visible) and times of contact. */
  visibility<T = unknown>(input: { lat: number; lon: number; startDate: string; endDate: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/eclipses/visibility", q.applyExtras(q.qNone(input), input, [["lat", "lat"], ["lon", "lon"], ["startDate", "start_date"], ["endDate", "end_date"]]), opts);
  }
}

class WesternHeliocentric {
  constructor(private readonly _c: ClientCore) {}

  /** Heliocentric (Sun-centred) planetary positions. */
  planets<T = unknown>(input: Types.WesternMomentInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/heliocentric/planets", q.qWesternMoment(input), opts);
  }
}

class WesternHoroscope {
  constructor(private readonly _c: ClientCore) {}

  /** Get the daily Western horoscope for a sun sign. */
  daily<T = unknown>(input: { sign: string; date: string; tone?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/horoscope/daily", q.applyExtras(q.qNone(input), input, [["sign", "sign"], ["date", "date"], ["tone", "tone"]]), opts);
  }

  /** Get the monthly Western horoscope for a sun sign. */
  monthly<T = unknown>(input: { sign: string; yearMonth: string; tone?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/horoscope/monthly", q.applyExtras(q.qNone(input), input, [["sign", "sign"], ["yearMonth", "year_month"], ["tone", "tone"]]), opts);
  }

  /** Get the weekly Western horoscope for a sun sign. */
  weekly<T = unknown>(input: { sign: string; weekStart: string; tone?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/horoscope/weekly", q.applyExtras(q.qNone(input), input, [["sign", "sign"], ["weekStart", "week_start"], ["tone", "tone"]]), opts);
  }
}

class WesternInterpretation {
  constructor(private readonly _c: ClientCore) {}

  /** Narrative interpretation for a natal/synastry aspect (e.g. Sun square Mars). */
  aspect<T = unknown>(input: { planetA: string; planetB: string; aspect: string; context?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/interpretation/aspect", q.applyExtras(q.qNone(input), input, [["planetA", "planet_a"], ["planetB", "planet_b"], ["aspect", "kind"], ["context", "context"]]), opts);
  }

  /** Narrative interpretation for a transiting planet aspecting a natal planet. */
  transit<T = unknown>(input: { transitPlanet: string; natalPlanet: string; aspect: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/interpretation/transit", q.applyExtras(q.qNone(input), input, [["transitPlanet", "transit_planet"], ["natalPlanet", "natal_planet"], ["aspect", "kind"]]), opts);
  }
}

class WesternLunar {
  constructor(private readonly _c: ClientCore) {}

  /** Get the natal Moon phase at birth — phase angle, illumination percentage, 8-named phase (new moon through waning crescent), and age in days since last new moon. */
  phase<T = unknown>(input: Types.WesternNatalInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/lunar/phase", q.qWesternNatal(input), opts);
  }
}

class WesternNarrative {
  constructor(private readonly _c: ClientCore) {}

  /** Get the authored narrative for a zodiac decan (10° division of a sign). */
  decan<T = unknown>(input: { sign: string; decan: number; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/narrative/decan", q.applyExtras(q.qNone(input), input, [["sign", "sign"], ["decan", "decan"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get the authored narrative interpretation for a named fixed star in a natal chart. */
  fixedStar<T = unknown>(input: { star: string; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>(q.buildPath("/v1/western/narrative/fixed-star/{star}", input, ["star"]), q.applyExtras(q.qNone(input), input, [["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get a composed narrative summary of a Western natal chart — authored prose covering Ascendant, Sun, Moon placements and key aspect highlights. */
  natalSummary<T = unknown>(input: Types.WesternNatalInput & { verbosity?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/narrative/natal-summary", q.applyExtras(q.qWesternNatal(input), input, [["verbosity", "verbosity"]]), opts);
  }

  /** Get the authored Sabian symbol and interpretation for a specific zodiac degree (1–360, where 1 = Aries 1° and 360 = Pisces 30°). */
  sabian<T = unknown>(input: { degree: number; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/narrative/sabian", q.applyExtras(q.qNone(input), input, [["degree", "degree"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get the Firdaria time-lord narrative for a given planet — the Hellenistic planetary period system (similar to Vimshottari but Ptolemaic). */
  timelordFirdaria<T = unknown>(input: { lord: string; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/narrative/timelord/firdaria", q.applyExtras(q.qNone(input), input, [["lord", "lord"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get the authored narrative for the annual profection house — a description of the life themes activated in this profection year. */
  timelordProfection<T = unknown>(input: { house: number; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/narrative/timelord/profection", q.applyExtras(q.qNone(input), input, [["house", "house"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get the authored narrative for a Zodiacal Releasing planetary lord — describes the life-period themes when a given planet is lord in the ZR system. */
  timelordZr<T = unknown>(input: { lord: string; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/narrative/timelord/zr", q.applyExtras(q.qNone(input), input, [["lord", "lord"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }

  /** Get a composed narrative summary of current transits to a natal chart — authored prose for the most exact active transits at the given moment. */
  transitSummary<T = unknown>(input: Types.NatalTransitInput & Types.VedicMomentSettings & { verbosity?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/narrative/transit-summary", q.applyExtras(q.qNatalTransit(input), input, [["verbosity", "verbosity"]]), opts);
  }

  /** Get the annual solar-return theme for a sun sign — a deep interpretive essay on the year's archetypal themes for that sign. */
  yearly<T = unknown>(input: { sign: string; lang?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/narrative/yearly", q.applyExtras(q.qNone(input), input, [["sign", "sign"], ["lang", "lang"], ["lang", "locale"]]), opts);
  }
}

class WesternNatal {
  constructor(private readonly _c: ClientCore) {}

  /** Antiscia (solstice points) and contra-antiscia. */
  antiscia<T = unknown>(input: Types.WesternNatalInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/natal/antiscia", q.qWesternNatal(input), opts);
  }

  /** Compute the Western (tropical) natal Ascendant — rising sign, degree, and Midheaven in the tropical zodiac. */
  ascendant<T = unknown>(input: Types.WesternNatalInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/natal/ascendant", q.qWesternNatal(input), opts);
  }

  /** Detect classical multi-planet aspect patterns in a natal chart — Grand Trine, T-Square, Grand Cross, Yod (Finger of God), Kite, Mystic Rectangle, Stellium, Grand Sextile. */
  aspectPatterns<T = unknown>(input: Types.WesternNatalInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/natal/aspect-patterns", q.qWesternNatal(input), opts);
  }

  /** All natal aspects with orbs and partile flags. */
  aspects<T = unknown>(input: Types.WesternNatalInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/natal/aspects", q.qWesternNatal(input), opts);
  }

  /** A single asteroid by MPC number. */
  asteroid<T = unknown>(input: Types.WesternNatalInput & { number: number | string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>(q.buildPath("/v1/western/natal/asteroid/{number}", input, ["number"]), q.qWesternNatal(input), opts);
  }

  /** Ceres, Pallas, Juno, Vesta plus Chiron. */
  asteroidsBigFourPlus<T = unknown>(input: Types.WesternNatalInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/natal/asteroids/big-four-plus", q.qWesternNatal(input), opts);
  }

  /** Get natal positions for the centaur bodies: Pholus, Nessus, Asbolus, and Chariklo. */
  centaurs<T = unknown>(input: Types.WesternNatalInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/natal/centaurs", q.qWesternNatal(input), opts);
  }

  /** Western (tropical) natal chart: planets, ascendant, MC, houses and aspects. */
  chart<T = unknown>(input: Types.WesternNatalInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/natal/chart", q.qWesternNatal(input), opts);
  }

  /** Classify the natal chart into one of the seven Jones planetary distribution patterns: Splash, Bundle, Locomotive, Bowl, Bucket, See-Saw, or Splay. */
  chartShape<T = unknown>(input: Types.WesternNatalInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/natal/chart-shape", q.qWesternNatal(input), opts);
  }

  /** Planetary declinations, parallels and out-of-bounds. */
  declinations<T = unknown>(input: Types.WesternNatalInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/natal/declinations", q.qWesternNatal(input), opts);
  }

  /** Get the chart dominance profile — dominant element (fire/earth/air/water), dominant modality (cardinal/fixed/mutable), most aspected planet, Lilly dignity ranking of traditional planets, and hemisphere balance. */
  dominant<T = unknown>(input: Types.WesternNatalInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/natal/dominant", q.qWesternNatal(input), opts);
  }

  /** Whether a named fixed star is conjunct any natal point. */
  fixedStar<T = unknown>(input: Types.WesternNatalInput & { name: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>(q.buildPath("/v1/western/natal/fixed-stars/{name}", input, ["name"]), q.qWesternNatal(input), opts);
  }

  /** Conjunctions between natal planets and major fixed stars. */
  fixedStars<T = unknown>(input: Types.WesternNatalInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/natal/fixed-stars", q.qWesternNatal(input), opts);
  }

  /** Nth harmonic chart (2-32). */
  harmonic<T = unknown>(input: Types.WesternNatalInput & { n: number | string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>(q.buildPath("/v1/western/natal/harmonic/{n}", input, ["n"]), q.qWesternNatal(input), opts);
  }

  /** Find harmonic aspects across multiple harmonics simultaneously — quintiles (H5), septiles (H7), noviles (H9), etc. */
  harmonicAspects<T = unknown>(input: Types.WesternNatalInput & { harmonics?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/natal/harmonic-aspects", q.applyExtras(q.qWesternNatal(input), input, [["harmonics", "harmonics"]]), opts);
  }

  /** Western tropical house cusps + Ascendant and MC. */
  houses<T = unknown>(input: Types.WesternNatalInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/natal/houses", q.qWesternNatal(input), opts);
  }

  /** Get all Lilith positions: Mean Black Moon Lilith, True Black Moon Lilith, Osculating (Interpolated) Lilith, and asteroid 1181 Lilith. */
  lilithSet<T = unknown>(input: Types.WesternNatalInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/natal/lilith-set", q.qWesternNatal(input), opts);
  }

  /** A single Arabic Lot (fortune|spirit|eros|...). */
  lot<T = unknown>(input: Types.WesternNatalInput & { name: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>(q.buildPath("/v1/western/natal/lot/{name}", input, ["name"]), q.qWesternNatal(input), opts);
  }

  /** All Hellenistic Arabic Parts (Lots). */
  lots<T = unknown>(input: Types.WesternNatalInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/natal/lots", q.qWesternNatal(input), opts);
  }

  /** Compute the Midheaven (Medium Coeli, MC) and its tropical sign for a Western birth chart — the career and public reputation point, along with its aspects to natal planets. */
  mc<T = unknown>(input: Types.WesternNatalInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/natal/mc", q.qWesternNatal(input), opts);
  }

  /** All planet-pair midpoints and activations. */
  midpoints<T = unknown>(input: Types.WesternNatalInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/natal/midpoints", q.qWesternNatal(input), opts);
  }

  /** Ebertin 90-degree dial midpoint tree. */
  midpointTree<T = unknown>(input: Types.WesternNatalInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/natal/midpoint-tree", q.qWesternNatal(input), opts);
  }

  /** Check which planets are Out of Bounds (OOB) in a Western natal chart — planets with declination beyond ±23°26′ (the Sun's maximum), considered to operate outside normal rules and with heightened, unconventional energy. */
  outOfBounds<T = unknown>(input: Types.WesternNatalInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/natal/out-of-bounds", q.qWesternNatal(input), opts);
  }

  /** Compute paran aspects — fixed stars crossing the 4 angles (Ascendant, MC, Descendant, IC) in parallel with natal planets. */
  parans<T = unknown>(input: Types.WesternNatalInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/natal/parans", q.qWesternNatal(input), opts);
  }

  /** Detail for a single Western natal planet. */
  planet<T = unknown>(input: Types.WesternNatalInput & { name: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>(q.buildPath("/v1/western/natal/planet/{name}", input, ["name"]), q.qWesternNatal(input), opts);
  }

  /** Get all planet placements in the Western (tropical) birth chart — sign, degree, house, retrograde flag, and speed for all 10 planets (Sun through Pluto) plus Chiron. */
  planets<T = unknown>(input: Types.WesternNatalInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/natal/planets", q.qWesternNatal(input), opts);
  }

  /** Get natal positions for trans-Neptunian objects: Eris, Sedna, Haumea, Makemake, Quaoar, Orcus, and Varuna. */
  tnos<T = unknown>(input: Types.WesternNatalInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/natal/tnos", q.qWesternNatal(input), opts);
  }

  /** Get positions for the eight Uranian/Hamburg school hypothetical planets: Cupido, Hades, Zeus, Kronos, Apollon, Admetos, Vulkanus, and Poseidon. */
  uranianHypotheticals<T = unknown>(input: Types.WesternNatalInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/natal/uranian-hypotheticals", q.qWesternNatal(input), opts);
  }

  /** Get the Vertex, Anti-Vertex, and East Point for a natal chart. */
  vertexSet<T = unknown>(input: Types.WesternNatalInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/natal/vertex-set", q.qWesternNatal(input), opts);
  }
}

class WesternPrimaryDirections {
  constructor(private readonly _c: ClientCore) {}

  /** Compute Placidus mundane primary directions — the promissor moves through the Placidus mundane house framework. */
  placidusMundane<T = unknown>(input: Types.WesternNatalInput & { key?: string; maxAge?: number; converse?: boolean }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/primary-directions/placidus-mundane", q.applyExtras(q.qWesternNatal(input), input, [["key", "key"], ["maxAge", "max_age"], ["converse", "converse"]]), opts);
  }

  /** Compute Placidus zodiacal primary directions — the oldest predictive technique in Western astrology (1° ≈ 1 year). */
  placidusZodiacal<T = unknown>(input: Types.WesternNatalInput & { key?: string; maxAge?: number; converse?: boolean }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/primary-directions/placidus-zodiacal", q.applyExtras(q.qWesternNatal(input), input, [["key", "key"], ["maxAge", "max_age"], ["converse", "converse"]]), opts);
  }

  /** Compute Regiomontanus primary directions — uses equatorial Right Ascension arc, the simplest and fastest calculation method. */
  regiomontanus<T = unknown>(input: Types.WesternNatalInput & { key?: string; maxAge?: number; converse?: boolean }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/primary-directions/regiomontanus", q.applyExtras(q.qWesternNatal(input), input, [["key", "key"], ["maxAge", "max_age"], ["converse", "converse"]]), opts);
  }
}

class WesternProfections {
  constructor(private readonly _c: ClientCore) {}

  /** Annual profections (Hellenistic time-lord); Ascendant advances one sign per year. */
  annual<T = unknown>(input: { birthDate: string; ascSign: string; refDate?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/profections/annual", q.applyExtras(q.qNone(input), input, [["birthDate", "birth_date"], ["ascSign", "asc_sign"], ["refDate", "ref_date"]]), opts);
  }

  /** Compute the daily profection drill-down — the most granular level of the profection system. */
  daily<T = unknown>(input: { birthDate: string; refDate?: string; ascSign: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/profections/daily", q.applyExtras(q.qNone(input), input, [["birthDate", "birth_date"], ["refDate", "ref_date"], ["ascSign", "asc_sign"]]), opts);
  }

  /** Compute the monthly profection sub-period — which house and lord are activated this month within the annual profection cycle. */
  monthly<T = unknown>(input: { birthDate: string; refDate?: string; ascSign: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/profections/monthly", q.applyExtras(q.qNone(input), input, [["birthDate", "birth_date"], ["refDate", "ref_date"], ["ascSign", "asc_sign"]]), opts);
  }
}

class WesternProgressions {
  constructor(private readonly _c: ClientCore) {}

  /** Get secondary progressed planet aspects to natal planets — the slow symbolic evolution of the birth chart over time. */
  aspectsToNatal<T = unknown>(input: Types.WesternNatalInput & { ageInYears: number }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/progressions/aspects-to-natal", q.applyExtras(q.qWesternNatal(input), input, [["ageInYears", "age_in_years"]]), opts);
  }

  /** Get the progressed Moon phase — shows what stage of the 29-year progressed lunation cycle you are in (new moon, crescent, first quarter, gibbous, full moon, disseminating, last quarter, balsamic). */
  lunation<T = unknown>(input: Types.WesternNatalInput & { ageInYears: number }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/progressions/lunation", q.applyExtras(q.qWesternNatal(input), input, [["ageInYears", "age_in_years"]]), opts);
  }

  /** Secondary progressed planetary positions at an age. */
  planets<T = unknown>(input: Types.WesternNatalInput & { ageInYears: number }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/progressions/planets", q.applyExtras(q.qWesternNatal(input), input, [["ageInYears", "age_in_years"]]), opts);
  }
}

class WesternReturns {
  constructor(private readonly _c: ClientCore) {}

  /** Compute the Lunar Return chart — the chart for the exact moment the transiting Moon returns to its natal degree (~every 27.3 days). */
  lunar<T = unknown>(input: Types.WesternNatalInput & { from: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/returns/lunar", q.applyExtras(q.qWesternNatal(input), input, [["from", "from"]]), opts);
  }

  /** Get the aspects formed between planets in the lunar return chart. */
  lunarAspects<T = unknown>(input: Types.WesternNatalInput & { from: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/returns/lunar/aspects", q.applyExtras(q.qWesternNatal(input), input, [["from", "from"]]), opts);
  }

  /** Solar Return chart for a year. */
  solar<T = unknown>(input: Types.WesternNatalInput & { returnYear: number }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/returns/solar", q.applyExtras(q.qWesternNatal(input), input, [["returnYear", "return_year"]]), opts);
  }

  /** Get the aspects formed between planets in the solar return chart — shows which planets are strongly configured in the return year. */
  solarAspects<T = unknown>(input: Types.WesternNatalInput & { returnYear: number }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/returns/solar/aspects", q.applyExtras(q.qWesternNatal(input), input, [["returnYear", "return_year"]]), opts);
  }

  /** Get the exact Julian Day (JD) and calendar datetime of the Western (tropical) solar return for a given year — the precise moment the Sun returns to its natal tropical longitude. */
  solarExactJd<T = unknown>(input: Types.WesternNatalInput & { year: number }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/returns/solar/exact-jd", q.applyExtras(q.qWesternNatal(input), input, [["year", "return_year"]]), opts);
  }
}

class WesternSolarArc {
  constructor(private readonly _c: ClientCore) {}

  /** Get solar arc directed planet aspects to natal planets — a predictive technique where all planets advance at the rate of the Sun (~1°/year). */
  aspectsToNatal<T = unknown>(input: Types.WesternNatalInput & { ageInYears: number }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/solar-arc/aspects-to-natal", q.applyExtras(q.qWesternNatal(input), input, [["ageInYears", "age_in_years"]]), opts);
  }

  /** Solar Arc directed planetary positions at an age. */
  planets<T = unknown>(input: Types.WesternNatalInput & { ageInYears: number }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/solar-arc/planets", q.applyExtras(q.qWesternNatal(input), input, [["ageInYears", "age_in_years"]]), opts);
  }
}

class WesternSynastry {
  constructor(private readonly _c: ClientCore) {}

  /** Cross-chart synastry aspects between two charts. */
  aspects<T = unknown>(input: Types.TwoPersonInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/synastry/aspects", q.qTwoPerson(input), opts);
  }

  /** Get the full N×M synastry aspect grid between two natal charts — every planet in chart A aspecting every planet in chart B. */
  grid<T = unknown>(input: Types.TwoPersonInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/synastry/grid", q.qTwoPerson(input), opts);
  }

  /** Synastry compatibility score and breakdown. */
  score<T = unknown>(input: Types.TwoPersonInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/synastry/score", q.qTwoPerson(input), opts);
  }
}

class WesternTransits {
  constructor(private readonly _c: ClientCore) {}

  /** Get a day-by-day calendar of transiting planet aspects to a natal chart over a date range (up to 30 days). */
  calendar<T = unknown>(input: Types.BirthInput & Types.VedicMomentSettings & { from: string; to: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/transits/calendar", q.applyExtras(q.qBirthPrefixed(input), input, [["from", "from"], ["to", "to"]]), opts);
  }

  /** Find the exact moment a transiting planet will aspect a natal planet — useful for precise transit timing. */
  exact<T = unknown>(input: Types.BirthInput & Types.VedicMomentSettings & { transitPlanet: string; natalPlanet: string; aspect: string; from: string; to: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/transits/exact", q.applyExtras(q.qBirthPrefixed(input), input, [["transitPlanet", "transit_planet"], ["natalPlanet", "natal_planet"], ["aspect", "aspect"], ["from", "from"], ["to", "to"]]), opts);
  }

  /** Current tropical planetary positions for transit analysis. */
  positions<T = unknown>(input: Types.WesternMomentInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/transits/positions", q.qWesternMoment(input), opts);
  }

  /** All current transiting aspects to natal planets. */
  toNatal<T = unknown>(input: Types.NatalTransitInput & Types.VedicMomentSettings, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/transits/to-natal", q.qNatalTransit(input), opts);
  }
}

class WesternZodiacalReleasing {
  constructor(private readonly _c: ClientCore) {}

  /** Zodiacal Releasing periods from the Lot of Fortune. */
  fortune<T = unknown>(input: { birthDate: string; lotSign: string; refDate?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/zodiacal-releasing/fortune", q.applyExtras(q.qNone(input), input, [["birthDate", "birth_date"], ["lotSign", "lot_sign"], ["refDate", "ref_date"]]), opts);
  }

  /** Compute Zodiacal Releasing from the Lot of Spirit — indicates career and achievement periods. */
  spirit<T = unknown>(input: { birthDate: string; refDate?: string; lotSign: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/zodiacal-releasing/spirit", q.applyExtras(q.qNone(input), input, [["birthDate", "birth_date"], ["refDate", "ref_date"], ["lotSign", "lot_sign"]]), opts);
  }
}

/** Western (tropical) astrology endpoints. */
export class Western {
  readonly astrocartography: WesternAstrocartography;
  readonly compatibility: WesternCompatibility;
  readonly composite: WesternComposite;
  readonly davison: WesternDavison;
  readonly dignities: WesternDignities;
  readonly eclipses: WesternEclipses;
  readonly heliocentric: WesternHeliocentric;
  readonly horoscope: WesternHoroscope;
  readonly interpretation: WesternInterpretation;
  readonly lunar: WesternLunar;
  readonly narrative: WesternNarrative;
  readonly natal: WesternNatal;
  readonly primaryDirections: WesternPrimaryDirections;
  readonly profections: WesternProfections;
  readonly progressions: WesternProgressions;
  readonly returns: WesternReturns;
  readonly solarArc: WesternSolarArc;
  readonly synastry: WesternSynastry;
  readonly transits: WesternTransits;
  readonly zodiacalReleasing: WesternZodiacalReleasing;

  constructor(private readonly _c: ClientCore) {
    this.astrocartography = new WesternAstrocartography(_c);
    this.compatibility = new WesternCompatibility(_c);
    this.composite = new WesternComposite(_c);
    this.davison = new WesternDavison(_c);
    this.dignities = new WesternDignities(_c);
    this.eclipses = new WesternEclipses(_c);
    this.heliocentric = new WesternHeliocentric(_c);
    this.horoscope = new WesternHoroscope(_c);
    this.interpretation = new WesternInterpretation(_c);
    this.lunar = new WesternLunar(_c);
    this.narrative = new WesternNarrative(_c);
    this.natal = new WesternNatal(_c);
    this.primaryDirections = new WesternPrimaryDirections(_c);
    this.profections = new WesternProfections(_c);
    this.progressions = new WesternProgressions(_c);
    this.returns = new WesternReturns(_c);
    this.solarArc = new WesternSolarArc(_c);
    this.synastry = new WesternSynastry(_c);
    this.transits = new WesternTransits(_c);
    this.zodiacalReleasing = new WesternZodiacalReleasing(_c);
  }

  /** Firdaria planetary periods (Persian time-lord cycle). */
  firdaria<T = unknown>(input: { birthDate: string; refDate?: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/firdaria", q.applyExtras(q.qNone(input), input, [["birthDate", "birth_date"], ["refDate", "ref_date"]]), opts);
  }

  /** All planetary sign-change ingresses in a date range. */
  ingresses<T = unknown>(input: Types.DateRangeInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/western/ingresses", q.qDateRange(input), opts);
  }

  /** Retrograde station windows for a planet in a date range. */
  retrogradeWindow<T = unknown>(input: Types.DateRangeInput & { planet: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>(q.buildPath("/v1/western/retrograde-window/{planet}", input, ["planet"]), q.qDateRange(input), opts);
  }
}
